### PR TITLE
Updated readme & fluent-ffmpeg package version

### PR DESCRIPTION
**Pull request by triniwiz**

### CODE REVIEW

**Comment by fishdude** [comment]
Thanks @triniwiz!

**Comment by triniwiz** [comment]
:)

**Comment by projectn00b** [comment]
@fishdude Has anyone been able to get this package to work with FS's transformWrite ? How do I use ffmpeg() with the stream or once it is uploaded to convert it?

**Comment by triniwiz** [comment]
There's an ffmpeg option to use a stream

**Comment by projectn00b** [comment]
Nevermind. Like 10 minutes after I wrote this I just read the node doc and found it. works like a charm. thanks.

**Pull request merged**
